### ISSUE TITLE
empty output file

### ISSUE THREAD

**Issue by LeandroRitter** [dakl/gatk#1]
Hi,

I ran the HeterozygoteConcordance walker on a vcf from the normal sample and a bam-file from a tumor sample and got surprisingly an empty output file like this

VARIANTSSAMPLE  READSSAMPLE     TOTAL_SNPS      HZ_SNP_COUNT    CONCORDANT_HZ_SNP_COUNT CONCORDANT_HZ_SNP_FRACTION

I get no error message from GATK. Those are the command lines I used

#EXTRACT SNPS FOR NORMAL SAMPLE FROM ONLY CHROMOSOME 21 TO A NEW VCF-FILE
vcftools --gzvcf /proj/b2015351/private/OK-0964/28G/04-VCF/28G.clean.dedup.recal.bam.recalibrated.snp.annotated.vcf.gz --chr 21 --out /proj/b2015351/private/devel_nikolay/28G_chr21 --recode --recode-INFO-all

#EXTRACT READS FOR TUMOR SAMPLE FROM ONLY CHROMOSOME 21 TO A NEW BAM-FILE AND INDEX THIS BAM-FILE
samtools view -h -b /proj/b2015351/private/OK-0964/28D/03-BAM/28D.clean.dedup.bam 21 > /proj/b2015351/private/devel_nikolay/28D_chr21.bam
samtools index 28D_chr21.bam

#RUN GATK HETEROZYGOTE-CONCORDANCE
java -jar /proj/b2015351/private/devel_nikolay/malin_larsson_scripts/GenomeAnalysisTK-Klevebring.jar \
-T HeterozygoteConcordance \
-V /proj/b2015351/private/devel_nikolay/28G_chr21.vcf \
-sid 28 \
-I /proj/b2015351/private/devel_nikolay/28D_chr21.bam \
-R /sw/data/uppnex/GATK/2.8/b37/human_g1k_v37.fasta \
-L /proj/b2015351/private/devel_nikolay/28G_chr21.vcf \
-o 28_HeterozygoteConcordance

Do you have an idea why I get no info after the walker finishes successfully?
Here is what GATK writes

[nikolay@milou2 devel_nikolay]$ java -jar /proj/b2015351/private/devel_nikolay/malin_larsson_scripts/GenomeAnalysisTK-Klevebring.jar -T HeterozygoteConcordance -V /proj/b2015351/private/devel_nikolay/28G_chr21.vcf -sid 28 -I /proj/b2015351/private/devel_nikolay/28D_chr21.bam -R /sw/data/uppnex/GATK/2.8/b37/human_g1k_v37.fasta -L /proj/b2015351/private/devel_nikolay/28G_chr21.vcf -o 28_HeterozygoteConcordance
INFO  22:32:07,137 HelpFormatter - ---------------------------------------------------------------------------------
INFO  22:32:07,146 HelpFormatter - The Genome Analysis Toolkit (GATK) v3.3-41-g9883132, Compiled 2015/02/10 20:05:53
INFO  22:32:07,147 HelpFormatter - Copyright (c) 2010 The Broad Institute
INFO  22:32:07,147 HelpFormatter - For support and documentation go to http://www.broadinstitute.org/gatk
INFO  22:32:07,156 HelpFormatter - Program Args: -T HeterozygoteConcordance -V /proj/b2015351/private/devel_nikolay/28G_chr21.vcf -sid 28 -I /proj/b2015351/private/devel_nikolay/28D_chr21.bam -R /sw/data/uppnex/GATK/2.8/b37/human_g1k_v37.fasta -L /proj/b2015351/private/devel_nikolay/28G_chr21.vcf -o 28_HeterozygoteConcordance
INFO  22:32:07,178 HelpFormatter - Executing as nikolay@milou2.uppmax.uu.se on Linux 2.6.32-642.4.2.el6.x86_64 amd64; Java HotSpot(TM) 64-Bit Server VM 1.7.0_25-b15.
INFO  22:32:07,178 HelpFormatter - Date/Time: 2016/09/14 22:32:07
INFO  22:32:07,188 HelpFormatter - ---------------------------------------------------------------------------------
INFO  22:32:07,188 HelpFormatter - ---------------------------------------------------------------------------------
INFO  22:32:07,657 GenomeAnalysisEngine - Strictness is SILENT
INFO  22:32:07,979 GenomeAnalysisEngine - Downsampling Settings: Method: BY_SAMPLE, Target Coverage: 1000
INFO  22:32:08,004 SAMDataSource$SAMReaders - Initializing SAMRecords in serial
INFO  22:32:08,067 SAMDataSource$SAMReaders - Done initializing BAM readers: total time 0.06
INFO  22:32:13,077 IntervalUtils - Processing 70798 bp from intervals
INFO  22:32:13,316 GenomeAnalysisEngine - Preparing for traversal over 1 BAM files
INFO  22:32:14,596 GenomeAnalysisEngine - Done preparing for traversal
INFO  22:32:14,597 ProgressMeter - [INITIALIZATION COMPLETE; STARTING PROCESSING]
INFO  22:32:14,598 ProgressMeter -                 | processed |    time |    per 1M |           |   total | remaining
INFO  22:32:14,598 ProgressMeter -        Location |     sites | elapsed |     sites | completed | runtime |   runtime
INFO  22:32:44,637 ProgressMeter -     21:10702880    640654.0    30.0 s      46.0 s       11.0%     4.6 m       4.1 m
INFO  22:33:14,668 ProgressMeter -     21:10799722   3089912.0    60.0 s      19.0 s       18.3%     5.5 m       4.5 m
INFO  22:33:44,673 ProgressMeter -     21:15920185   4199212.0    90.0 s      21.0 s       32.1%     4.7 m       3.2 m
INFO  22:34:14,678 ProgressMeter -     21:27566802   4565751.0   120.0 s      26.0 s       58.0%     3.4 m      86.0 s
INFO  22:34:44,687 ProgressMeter -     21:40715831   4837965.0     2.5 m      31.0 s       80.7%     3.1 m      35.0 s
INFO  22:35:08,160 HeterozygoteConcordance - Traversed 56279 variant positions from the VCF.
INFO  22:35:08,192 ProgressMeter -            done   5117413.0     2.9 m      33.0 s      100.0%     2.9 m       0.0 s
INFO  22:35:08,192 ProgressMeter - Total runtime 173.60 secs, 2.89 min, 0.05 hours
INFO  22:35:08,193 MicroScheduler - 520260 reads were filtered out during the traversal out of approximately 2909331 total reads (17.88%)
INFO  22:35:08,193 MicroScheduler -   -> 415602 reads (14.29% of total) failing DuplicateReadFilter
INFO  22:35:08,193 MicroScheduler -   -> 0 reads (0.00% of total) failing FailsVendorQualityCheckFilter
INFO  22:35:08,214 MicroScheduler -   -> 0 reads (0.00% of total) failing MalformedReadFilter
INFO  22:35:08,215 MicroScheduler -   -> 103327 reads (3.55% of total) failing NotPrimaryAlignmentFilter
INFO  22:35:08,215 MicroScheduler -   -> 1331 reads (0.05% of total) failing UnmappedReadFilter

**Comment by LeandroRitter** [comment]
Sorry, just realized that the -sid flag must have not just any name but
exactly the one on the 10-th column in the normal sample VCF, which was in my case 28G and not just 28. Now everything worked fine and concordance was about 95%.

**Comment by dakl** [comment]
Glad to hear it's working 👍
